-- Drivers Table
-- Stores driver-specific information and verification details
CREATE TABLE IF NOT EXISTS drivers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    license_number VARCHAR(50) UNIQUE NOT NULL,
    license_expiry DATE NOT NULL,
    vehicle_type ENUM('car', 'motorcycle', 'tricycle', 'bus') NOT NULL,
    vehicle_make VARCHAR(50) NOT NULL,
    vehicle_model VARCHAR(50) NOT NULL,
    vehicle_year YEAR NOT NULL,
    vehicle_color VARCHAR(30) NOT NULL,
    vehicle_plate_number VARCHAR(20) UNIQUE NOT NULL,
    insurance_number VARCHAR(50) NOT NULL,
    insurance_expiry DATE NOT NULL,
    emergency_contact_name VARCHAR(100) NOT NULL,
    emergency_contact_phone VARCHAR(20) NOT NULL,
    address TEXT NOT NULL,
    city VARCHAR(100) NOT NULL,
    region VARCHAR(100) NOT NULL,
    verification_status ENUM('pending', 'approved', 'rejected', 'suspended') DEFAULT 'pending',
    background_check_status ENUM('pending', 'approved', 'failed') DEFAULT 'pending',
    driver_rating DECIMAL(3,2) DEFAULT 0.00,
    total_trips INT DEFAULT 0,
    is_online BOOLEAN DEFAULT FALSE,
    current_latitude DECIMAL(10,8) DEFAULT NULL,
    current_longitude DECIMAL(11,8) DEFAULT NULL,
    last_location_update TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_user_id (user_id),
    INDEX idx_license (license_number),
    INDEX idx_plate (vehicle_plate_number),
    INDEX idx_verification (verification_status),
    INDEX idx_background_check (background_check_status),
    INDEX idx_online (is_online),
    INDEX idx_location (current_latitude, current_longitude),
    INDEX idx_rating (driver_rating),
    INDEX idx_city_region (city, region)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;